// Generated by CoffeeScript 1.10.0
(function() {
  var Main, main;

  String.prototype.startsWith = function(str) {
    return this.slice(0, str.length) === str;
  };

  String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
  };

  Main = (function() {
    function Main() {}

    Main.prototype.run = function() {
      var dict, file, fileName, root;
      root = app.activeDocument;
      fileName = File.openDialog("tsv選択", "*.tsv");
      if (fileName) {
        file = new File(fileName);
        dict = this.createDict(file);
        return this.setLayerName(root, dict);
      }
    };

    Main.prototype.createDict = function(file) {
      var dict, elements;
      file.encoding = "SHIFT-JIS";
      file.open("r", "TEXT");
      dict = {};
      while (!file.eof) {
        elements = file.readln().split('\t');
        dict[elements[0]] = elements[1];
      }
      return dict;
    };

    Main.prototype.setLayerName = function(root, dict) {
      var i, len, ref, results, text, textFrame;
      ref = root.textFrames;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        textFrame = ref[i];
        if (textFrame.locked) {
          continue;
        }
        text = textFrame.contents.replace(/[\n\r]+/g, ' ');
        if (dict[text]) {
          results.push(textFrame.name = dict[text]);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return Main;

  })();

  main = new Main();

  main.run();

  alert('complete!');

}).call(this);
