// Generated by CoffeeScript 1.10.0
(function() {
  var Main, main;

  String.prototype.startsWith = function(str) {
    return this.slice(0, str.length) === str;
  };

  String.prototype.endsWith = function(suffix) {
    return this.indexOf(suffix, this.length - suffix.length) !== -1;
  };

  Main = (function() {
    function Main() {}

    Main.prototype.run = function() {
      var file, fileName, root;
      root = app.activeDocument;
      fileName = File.saveDialog("保存先指定(*.tsv)");
      if (fileName) {
        file = new File(fileName);
        file.encoding = "SHIFT-JIS";
        file.open("w", "TEXT");
        this["export"](root, file);
        return file.close();
      }
    };

    Main.prototype["export"] = function(root, file) {
      var i, len, ref, results, textFrame;
      ref = root.textFrames;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        textFrame = ref[i];
        if (textFrame.contents.replace(/[\n\r]+/g, ' ').replace(/ /, '') === "") {
          continue;
        }
        results.push(file.write((textFrame.contents.replace(/[\n\r]+/g, ' ')) + "\t\n"));
      }
      return results;
    };

    return Main;

  })();

  main = new Main();

  main.run();

  alert('complete!');

}).call(this);
