// Generated by CoffeeScript 1.10.0
(function() {
  var Importer, KEY, VALUE, importer;

  KEY = "Key";

  VALUE = "Value";

  Importer = (function() {
    function Importer() {}

    Importer.prototype.run = function() {
      var dict, root;
      root = app.activeDocument;
      dict = this.readCSV();
      return this.replaceText(dict, root);
    };

    Importer.prototype.readCSV = function() {
      var dict, e, elements, file, i, index, key, keyIndex, len, value, valueIndex;
      file = File.openDialog("Select a file", "*");
      file.open('r');
      dict = {};
      keyIndex = 0;
      valueIndex = 0;
      elements = file.readln().split(',');
      for (index = i = 0, len = elements.length; i < len; index = ++i) {
        e = elements[index];
        if (e === KEY) {
          keyIndex = index;
        }
        if (e === VALUE) {
          valueIndex = index;
        }
      }
      while (!file.eof) {
        elements = file.readln().split(',');
        key = elements[keyIndex];
        value = elements[valueIndex];
        if (key === "") {
          continue;
        }
        if (dict[key]) {
          if (value === "") {
            continue;
          }
          dict[key] += "\n";
          dict[key] += value;
        } else {
          dict[key] = value;
        }
      }
      file.close();
      return dict;
    };

    Importer.prototype.replaceText = function(dict, root) {
      var i, len, ref, results, textFrame;
      ref = root.textFrames;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        textFrame = ref[i];
        if (dict[textFrame.name]) {
          results.push(textFrame.contents = dict[textFrame.name]);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return Importer;

  })();

  importer = new Importer();

  importer.run();

  alert('complete!');

}).call(this);
